baseURL = 'https://yuushaexa.github.io/vnovel'
languageCode = 'en-us'
title = "GameLibrary"
theme = "database"  
[params]
    description = "Games Library"
    author = "Yuusha"
    [security]
[security.gotemplates]
allowActionJSTmpl = true
[pagination]
  pagerSize = 500
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
            [outputs]
home = [ "HTML" ]
            
            [taxonomies]
    tag = "tags"
    category = "categories"
    genres = "genres"
    publisher = "publisher"
    developer = "developer"
    gametype = "gametype"
    year = "year"
